### 심리테스트 유형 추가
POST localhost:7070/posts
Content-Type: application/json

{
  "imgUrl": "이미지주소",
  "posterTitle": "4",
  "passage": ""
}

### 심리테스트 유형 조회
GET localhost:7070/posts

### 심리테스트 조회수 증가
PUT localhost:7070/posts/1